[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = {path = "../domain" }
aws-config = "1.8.11"
aws-sdk-dynamodb = "1.123.0"
aws-sdk-s3 = "1.91.0"
tokio = { version = "1.53.1", features = ["full"] }
async-trait = "0.1.92"
bcrypt = "0.19.3"
chrono = { version = "0.4", features = ["serde"] }
